# Generated by Django 5.1.4 on 2024-12-08 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=255)),
                ('user_name', models.CharField(default='user', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='user', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_page', models.URLField(blank=True, verbose_name='Home Page')),
                ('captcha', models.CharField(default='', max_length=48, verbose_name='CAPTCHA')),
                ('image', models.ImageField(blank=True, help_text='Upload an image (optional)', null=True, upload_to='comment_images', verbose_name='Upload Image')),
                ('text_file', models.FileField(blank=True, help_text='Upload a text file (optional)', null=True, upload_to='comment_text_files', verbose_name='Upload Text File')),
                ('client_info', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='comments.clientinfo')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_to', to='comments.comment')),
            ],
        ),
    ]
